---
- hosts: 172.31.87.217
  become: yes
  tasks: 
  - name: i want to run a comment 
    command: hostname -f
    register: resultforcom

  - name: i want to display my first task result 
    debug: 
      msg: "{{resultforcom}}"

  - name: i want to install git 
    apt:
       name: git
       state: present
    when: resultforcom.stderr ==""

  - name: i want to install tree  
    apt:
       name: tree
       state: present
    when: resultforcom.stderr !=""