--- 
- name: file handeling
  hosts: mywebserver
  become: yes 
  tasks:
   - include_tasks: myfileee.yml 
   - name: want to copy a file to ansible node
     copy: 
       src: myststic.txt
       dest: /root/myansible

 