--- 
- name: file handeling
  hosts: 172.31.87.217 
  become: yes 
  tasks:
   - include_tasks: myfileee.yml 
   - name: want to copy a file to ansible node
     copy: 
       src: myststic.txt
       dest: /root/myansible

   - name: install apache2
     apt:
       name: apache2
       state: present      
   - name: i wwant to create a dyno file in to ansible node 
     template:
       src: mydyno.j2
       dest: /var/www/html/index.html