---
- hosts: 172.31.87.217
  become: yes
  tasks:
   - name: install wget
     apt:
       name: wget
       state: present 

   - name: install tree
     apt: 
       name: tree
       state: present 

   - name: install git
     apt: 
       name: git 
       state: present      
           