---
- hosts: all
  become: yes
  tasks: 
  - name: i want to install webserver
    apt:
      name: apache2
      state: present
    when: ansible_os_family =="Debian"         
   
  - name: i want to start a service 
    service: 
       name: apache2
       state: started
    when: ansible_os_family =="Debian"

  - name: i want to install web server on redhat
    yum:
      name: httpd
      state: started
    when:  ansible_os_family =="redhat" 

  - name: i want to start web server on red hat
    service: 
       name: httpd
       state: started
    when: ansible_os_family =="redhat"