---
- hosts: mywebserver
  become: yes
  tasks: 
  - name: i want to install webserver
    apt:
      name: "{{sat}}"
      state: present
    when: ansible_os_family =="Debian"         
   
  - name: i want to start a service 
    service: 
       name: "{{sat}}"
       state: started
    when: ansible_os_family =="Debian"

  - name: i want to install web server on redhat
    yum:
      name: "{{bat}}"
      state: present
    when:  ansible_os_family =="RedHat" 

  - name: i want to start web server on red hat
    service: 
       name: "{{bat}}"
       state: started
    when: ansible_os_family =="RedHat"